# Generated by Django 4.2.6 on 2023-10-26 21:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('bok_id', models.AutoField(primary_key=True, serialize=False)),
                ('bok_date', models.DateTimeField(default=datetime.datetime.now)),
                ('bok_amt', models.TextField()),
                ('bok_curr_id', models.BigIntegerField(blank=True, null=True)),
                ('bok_note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'booking',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BookingStatus',
            fields=[
                ('status_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status_name_en', models.TextField()),
                ('status_name_ar', models.TextField()),
            ],
            options={
                'db_table': 'booking_status',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cln_name_en', models.TextField()),
                ('cln_name_ar', models.TextField()),
            ],
            options={
                'db_table': 'clinic',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('dct_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dct_name_en', models.TextField()),
                ('dct_desc', models.TextField()),
                ('dct_desc_en', models.TextField(null=True)),
                ('dct_desc_ar', models.TextField(null=True)),
                ('dct_img_url', models.TextField()),
                ('dct_phone', models.TextField()),
                ('dct_name_ar', models.TextField()),
                ('dct_clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Clinc_API.clinic')),
            ],
            options={
                'db_table': 'doctor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('doc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('doc_name_en', models.TextField()),
                ('doc_name_ar', models.TextField()),
                ('doc_url', models.TextField()),
            ],
            options={
                'db_table': 'document',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('gnd_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gnd_name_en', models.TextField()),
                ('gnd_name_ar', models.TextField()),
            ],
            options={
                'db_table': 'gender',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InsuranceCompanies',
            fields=[
                ('insurance_number', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_name', models.TextField(max_length=100)),
                ('phone_number', models.TextField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'InsuranceCompanies',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('major_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('major_name_ar', models.TextField()),
                ('major_name_en', models.TextField()),
            ],
            options={
                'db_table': 'major',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('pnt_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pnt_age', models.IntegerField()),
                ('pnt_img_url', models.TextField(blank=True)),
                ('pnt_phone', models.TextField(unique=True)),
                ('pnt_email', models.TextField(unique=True)),
                ('pnt_name_ar', models.TextField()),
                ('pnt_isr_doc_img', models.ImageField(blank=True, null=True, upload_to='images/pnt/')),
                ('pnt_name_en', models.TextField()),
                ('has_insurance', models.BooleanField(default=False)),
                ('pnt_insurance_num', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('pnt_gender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Clinc_API.gender')),
                ('pnt_insurance_co', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Clinc_API.insurancecompanies')),
            ],
            options={
                'db_table': 'patient',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('pym_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pym_name_en', models.TextField()),
                ('pym_name_ar', models.TextField()),
            ],
            options={
                'db_table': 'payment_method',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PracticingProfession',
            fields=[
                ('practice_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('practicing_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
            ],
            options={
                'db_table': 'PracticingProfession',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Action', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'Services',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsersSystem',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('usr_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('usr_age', models.IntegerField()),
                ('usr_img_url', models.TextField(blank=True)),
                ('usr_phone', models.TextField(unique=True)),
                ('usr_email', models.TextField(blank=True, null=True, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('desc', models.TextField(blank=True, default=None, null=True)),
                ('name_ar', models.TextField(blank=True, default=None, null=True)),
                ('name_en', models.TextField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('usr_type', models.BigIntegerField()),
                ('is_superuser', models.BooleanField(default=False)),
                ('clinic', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Clinc_API.clinic')),
                ('gender', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Clinc_API.gender')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('is_doctor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Clinc_API.doctor')),
                ('is_patient', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Clinc_API.patient')),
                ('major', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Clinc_API.major')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users_system',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('sin_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sin_date', models.DateTimeField()),
                ('sin_bok', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Clinc_API.booking')),
                ('sin_doc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Clinc_API.document')),
            ],
            options={
                'db_table': 'session',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('doc_serial', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=100)),
                ('rcp_as_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('check_number', models.CharField(blank=True, max_length=20, null=True)),
                ('invoice_number', models.CharField(max_length=20)),
                ('transaction_number', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Clinc_API.paymentmethod')),
                ('rcp_cst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Clinc_API.patient')),
            ],
            options={
                'db_table': 'receipt',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='dct_gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Clinc_API.gender'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='dct_major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Clinc_API.major'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='practicing_profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Clinc_API.practicingprofession'),
        ),
        migrations.AddField(
            model_name='booking',
            name='bok_dct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Clinc_API.doctor'),
        ),
        migrations.AddField(
            model_name='booking',
            name='bok_pnt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Clinc_API.patient'),
        ),
        migrations.AddField(
            model_name='booking',
            name='bok_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Clinc_API.bookingstatus'),
        ),
    ]
