# Generated by Django 4.2.5 on 2023-10-10 02:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('bok_id', models.AutoField(primary_key=True, serialize=False)),
                ('bok_date', models.DateTimeField(default=datetime.datetime.now)),
                ('bok_amt', models.TextField()),
                ('bok_curr_id', models.BigIntegerField(blank=True, null=True)),
                ('bok_note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'booking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookingStatus',
            fields=[
                ('status_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status_name_en', models.TextField()),
                ('status_name_ar', models.TextField()),
            ],
            options={
                'db_table': 'booking_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('doc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('doc_name_en', models.TextField()),
                ('doc_name_ar', models.TextField()),
                ('doc_url', models.TextField()),
            ],
            options={
                'db_table': 'document',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('sin_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sin_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cln_name_en', models.TextField()),
                ('cln_name_ar', models.TextField()),
            ],
            options={
                'db_table': 'clinic',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('dct_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dct_name_en', models.TextField()),
                ('dct_desc', models.TextField()),
                ('dct_img_url', models.TextField()),
                ('dct_phone', models.TextField()),
                ('dct_name_ar', models.TextField()),
                ('dct_clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Clinc_API.clinic')),
            ],
            options={
                'db_table': 'doctor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('gnd_id', models.AutoField(primary_key=True, serialize=False)),
                ('gnd_name_en', models.TextField()),
                ('gnd_name_ar', models.TextField()),
            ],
            options={
                'db_table': 'gender',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('major_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('major_name_ar', models.TextField()),
                ('major_name_en', models.TextField()),
            ],
            options={
                'db_table': 'major',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('pnt_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pnt_age', models.IntegerField()),
                ('pnt_img_url', models.TextField(blank=True)),
                ('pnt_phone', models.TextField(unique=True)),
                ('pnt_email', models.TextField(unique=True)),
                ('pnt_name_ar', models.TextField()),
                ('pnt_name_en', models.TextField()),
                ('pnt_gender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Clinc_API.gender')),
            ],
            options={
                'db_table': 'patient',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsersSystem',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('usr_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('usr_age', models.IntegerField()),
                ('usr_img_url', models.TextField(blank=True)),
                ('usr_phone', models.TextField(unique=True)),
                ('usr_email', models.TextField(blank=True, null=True, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('desc', models.TextField(blank=True, default=None, null=True)),
                ('name_ar', models.TextField(blank=True, default=None, null=True)),
                ('name_en', models.TextField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('usr_type', models.BigIntegerField()),
                ('is_superuser', models.BooleanField(default=False)),
                ('clinic', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Clinc_API.clinic')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('is_doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Clinc_API.doctor')),
                ('is_patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Clinc_API.patient')),
                ('major', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Clinc_API.major')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('usr_gender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Clinc_API.gender')),
            ],
            options={
                'db_table': 'users_system',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='dct_gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Clinc_API.gender'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='dct_major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Clinc_API.major'),
        ),
    ]
