# Generated by Django 4.2.5 on 2023-10-10 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clinc_API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='dct_gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Clinc_API.gender'),
        ),
        migrations.AlterField(
            model_name='gender',
            name='gnd_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userssystem',
            name='is_doctor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Clinc_API.doctor'),
        ),
        migrations.AlterField(
            model_name='userssystem',
            name='is_patient',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Clinc_API.patient'),
        ),
        migrations.AlterField(
            model_name='userssystem',
            name='usr_gender',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Clinc_API.gender'),
        ),
    ]
