# Generated by Django 4.2.5 on 2023-10-10 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clinc_API', '0002_alter_doctor_dct_gender_alter_gender_gnd_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userssystem',
            old_name='usr_gender',
            new_name='gender',
        ),
    ]
