# Generated by Django 4.2.6 on 2023-10-10 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clinc_API', '0003_rename_usr_gender_userssystem_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userssystem',
            name='is_doctor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Clinc_API.doctor'),
        ),
        migrations.AlterField(
            model_name='userssystem',
            name='is_patient',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Clinc_API.patient'),
        ),
    ]
