# Generated by Django 4.2.6 on 2023-10-11 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clinc_API', '0004_alter_userssystem_is_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='dct_clinic_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Clinc_API.clinic'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='dct_clinic_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Clinc_API.clinic'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='dct_gender_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Clinc_API.gender'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='dct_gender_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Clinc_API.gender'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='dct_major_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Clinc_API.major'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='dct_major_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Clinc_API.major'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='dct_name_ar_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='dct_name_ar_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='dct_name_en_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='dct_name_en_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='dct_phone_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='dct_phone_en',
            field=models.TextField(null=True),
        ),
    ]
