# Generated by Django 4.2.6 on 2023-10-11 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clinc_API', '0005_doctor_dct_clinic_ar_doctor_dct_clinic_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='dct_clinic_ar',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='dct_clinic_en',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='dct_gender_ar',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='dct_gender_en',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='dct_major_ar',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='dct_major_en',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='dct_phone_ar',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='dct_phone_en',
        ),
    ]
