# Generated by Django 4.2.6 on 2023-10-11 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clinc_API', '0006_remove_doctor_dct_clinic_ar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='dct_name_ar_ar',
            new_name='dct_desc_ar',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='dct_name_ar_en',
            new_name='dct_desc_en',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='dct_name_en_ar',
            new_name='dct_phone_ar',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='dct_name_en_en',
            new_name='dct_phone_en',
        ),
    ]
