# Generated by Django 4.2.6 on 2023-10-11 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clinc_API', '0007_rename_dct_name_ar_ar_doctor_dct_desc_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='dct_phone_ar',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='dct_phone_en',
        ),
    ]
